### ISSUE TITLE
Fails to build on Xcode 10.2 beta 1

### ISSUE THREAD

**Issue by b3ll** [stephan-tolksdorf/STULabel#3]
Some new C++ stuff seems to have been changed but I don't really understand a lot of the template stuff you wrote :P 

Any chance you could take a look? 

Thanks!

```
STULabel/STULabel/Internal/NSStringRef.hpp:105:41: note: in instantiation of exception specification for 'operator _NSRange<_NSRange, unsigned long, 0>' requested here
        copyUTF16Chars_slowPath(NSRange(utf16IndexRange), out.begin());
```

**Comment by stephan-tolksdorf** [comment]
Thanks for the report! I'll take a look later today.

**Comment by stephan-tolksdorf** [comment]
I've fixed the errors caused by the casts and some other warnings. However, there seems to be a new bug in the Swift compiler that affects the overloaded initializers of `STUBackgroundAttribute` and `STUTextHighlightStyleBuilder`. If you're using Swift, you can temporarily work around these bugs e.g. by giving the closure arguments in the respective `.overlay.swift` extensions a name and changing the call sites accordingly.

I didn't yet have a chance to test STULabel on iOS 12.2. Please let me know when you spot an issue.

**Comment by stephan-tolksdorf** [comment]
I've created a Swift JIRA ticket: https://bugs.swift.org/browse/SR-9785

**Comment by b3ll** [comment]
Thanks so much for fixing that! I'll give some tests on device but they seem OK currently
